name: Release Workflow
on: [create]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get install -y autoconf
      - name: Install configure
        run: ./autogen.sh && ./configure CFLAGS="-static"
      - name: Build
        run: make LDFLAGS="--static"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/mkfs.fat,src/fsck.fat,src/fatlabel,src/testdevinfo"
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true